management:
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
      enabled: true
  health:
    db: true
    defaults:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - db
          - info

